### ISSUE TITLE
Search Article.

### ISSUE THREAD

**Issue by jsgao0** [f2etw/weekly-collection#16]
要不要開始著手?
https://github.com/christian-fei/Simple-Jekyll-Search
http://jekyll.tips/tutorials/search/

**Comment by Rplus** [comment]
jekyll 要搜尋可以直接爬 feed.xml
或是導去 google 搜尋就好

不過要考慮的是，有需要搜尋什麼嗎？

**Comment by jsgao0** [comment]
搜尋的方式都可，只是為了使用者在篩選資訊的方便性。
要找看過的文章較容易，否則要跟Facebook的介面一樣，不斷手動往前找。

**Comment by Rplus** [comment]
瞭解~
那做吧~  ( 快送 PR 來吧 XDDD
