### ISSUE TITLE
留言系統

### ISSUE THREAD

**Issue by Rplus** [f2etw/weekly-collection#27]
或許需要一個留言的地方~

jekyll.now 有提供 disqus 的 template
不曉得是不是直接開這就好？

**Comment by Clementtang** [comment]
太晚看到，我本來想說用 Facebook 留言就好 XD？不然這樣還得要多管理一個 Disqus 帳號。

**Comment by Rplus** [comment]
我本來也打算用 FB 的~
不過 jekyll 的 template 裡有 Disqus 的模版
就直接拿來用了 XDDD

@Clementtang 你應該可以用 Facebook 登 Disqus 吧~

PS: 申請 FB 留言也是要管理一個 FB APP 吶~

**Comment by Clementtang** [comment]
可以用 Disqus 阿，不過我有點忘了之前在找留言系統的時候，為何大家會推薦 FB 而非 Disqus，好像有些原因。

管理 FB APP 只需要 FB 帳號就好，而且可以直接加其他 FB 帳號當管理者，但是 Disqus 要另外用 Email？印象中是這樣。

**Comment by Rplus** [comment]
其實我對 FB 帳號的穩定性抱持懷疑吶~
不小心就被 FB 鎖帳號的也不是不常聽說…
