### ISSUE TITLE
自動撈時間區段裡的熱門文章

### ISSUE THREAD

**Issue by Rplus** [f2etw/weekly-collection#3]
目前預計每週要撈前二十篇熱門的文章
看來手動去捲應該蠻累的
不曉得有沒有什麼自動化的操作可以幫忙先爬出這些文章來~

**Comment by amazingandyyy** [comment]
Just mark this, looks like about how to pull content in the feed of a group
https://developers.facebook.com/docs/graph-api/reference/v2.5/group/feed

**Comment by Rplus** [comment]
目前先這樣~
複製貼上的動作可能會稍微繁瑣一些

https://github.com/f2etw/weekly-collection/wiki/%E7%A4%BE%E5%9C%98%E7%86%B1%E9%96%80%E8%B2%BC%E6%96%87%E7%9A%84%E8%B3%87%E6%96%99%E6%95%B4%E7%90%86

close #3

**Comment by Rplus** [comment]
目前先這樣~
複製貼上的動作可能會稍微繁瑣一些

https://github.com/f2etw/weekly-collection/wiki/%E7%A4%BE%E5%9C%98%E7%86%B1%E9%96%80%E8%B2%BC%E6%96%87%E7%9A%84%E8%B3%87%E6%96%99%E6%95%B4%E7%90%86

close #3
