### ISSUE TITLE
Weekly collection 信件沒有內容

### ISSUE THREAD

**Issue by ShinyChang** [f2etw/weekly-collection#45]
如圖：

![image](https://cloud.githubusercontent.com/assets/1590707/14791015/8bc57ca8-0b46-11e6-8462-40538a1d46c5.png)

看起來是 replace 失敗

**Comment by Rplus** [comment]
O_Q
目前是 jekyll-now 預設設定
它直接套用這個 gem
https://github.com/jekyll/jekyll-feed

可能要找個時間來看看
它這支是在寫什麼玩意
https://github.com/jekyll/jekyll-feed/blob/master/lib%2Ffeed.xml

不然的話可能要自己照樣刻一支自己的 feed.xml

**Comment by Rplus** [comment]
新的 `feed.xml` 推上去了
不確定 Gmail 的解析會不會正常
就實驗看看吧~ ：P

**Comment by Rplus** [comment]
嗯~ 收到信了~
看樣子跟預期的一致，還算不錯~
![image](https://cloud.githubusercontent.com/assets/1808835/14957505/456c2c76-10b8-11e6-8960-4cb180e0ded4.png)
